spring:
  profiles:
    include:
      core
    active: dev
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 200

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}

exchange-rate:
  api:
    url: ${EXCHANGE_RATE_API_URL}
    key: ${EXCHANGE_RATE_API_KEY}
