
### 비밀번호 변경 요청
PATCH http://localhost:8080/v1/member/change-password
Content-Type: application/json
Authorization: eyJraWQiOiJrZXkzIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MTIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNTM5MTc2MSwiZXhwIjoxNzA1NTM1NzYxfQ.qj1E_jDYpQI7a8ggUCP4mjuQgADVglgsCTyaQ9J5lF0

{
  "confirmPassword": "1234567",
  "newPassword": "1234567"
}


### 비밀번호 체크 요청
POST http://localhost:8080/v1/member/check-password
Content-Type: application/json
Authorization: eyJraWQiOiJrZXkzIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MTIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNTM5MTc2MSwiZXhwIjoxNzA1NTM1NzYxfQ.qj1E_jDYpQI7a8ggUCP4mjuQgADVglgsCTyaQ9J5lF0

{
  "newPassword": "12345678",
  "confirmPassword": "12345678"
}

