### 회원가입
POST http://localhost:8080/v1/member/signup
Content-Type: application/json

{
  "email": "test123@naver.com",
  "password": "123456"
}

### 이메일 중복 체크
GET http://localhost:8080/v1/member/check-duplicated-email?email=test1@naver.com
Content-Type: application/json